image: python:3.9

pipelines:
  default:
    - step:
        name: Run Telegram Bot
        script:
          - chmod +x *  # Make all scripts executable
          - pip install python-telegram-bot
          - python nuclear.py
         
